### PR TITLE
use recipes instead of depending on Plots

### PR DESCRIPTION
**Pull request by BeastyBlacksmith**
Also fixed precompilation issues due to double include and renamed `pattern` to match usual conventions.

This should get a breaking release (so either 0.2 or 1.0)

### CODE REVIEW

**Review by CNelias — CHANGES_REQUESTED** [review]
Thanks for the changes. Didn't know about the recipes macro, it's very useful!
Might I ask why you'd like to rename 'plot_motif' to 'plot'? And if so I guess the function name should also be changed to 'plot' instead of 'plot_motif'.

**Comment by BeastyBlacksmith** [comment]
Well, the name of the function doesn't matter. What `@recipe` does is to create a new method for`RecipesBase.apply_recipe` which in turn will get called by `Plots.plot`.

More information in https://daschw.github.io/recipes/

**Comment by CNelias** [comment]
I see. but it still needs to be consistent. In the readme, you changed 'plot_motif' to 'plot' but in 'MotifRecognition.jl' the function is still called 'plot_motif'. 
Unless I missed something, this might be a problem if someone tries to copy/paste and run the code from the readme.

**Comment by BeastyBlacksmith** [comment]
The readme works fine. With this change `MotifRecognition` neither has a `plot_motif` function nor a `plot` function.

The `plot` function the readme belongs to `Plots` while the name `plot_motif` in `MotifRecognition.jl` gets discarded by the `@recipe` macro, it only serves a documentary purpose now.

**Comment by CNelias** [comment]
I see, then I need to read the recipes doc again.

**Pull request merged**
